<a href="https://colab.research.google.com/github/FaizaAli-Dev/AI-DS-Projects/blob/All-about-AI-and-Data-Science/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To use numpy library we have to import numpy pakages



In [ ]:
import numpy as np
from numpy import array

1-dim arrays

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])  # Create a rank 1 array
print(a)

[1 2 3 4 5 6]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a[0])

1


In [ ]:
import numpy as np
i=np.ones((2,3))
print(i)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
bool_idx=(i>2)
print(bool_idx)

[[False False False]
 [False False False]]


In [ ]:
a2=np.array([372,4,4,5])
print(a2[a2>50])

[372]


In [ ]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [ ]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
print(np.dot(x,y))
print(x@y)

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [ ]:
print(x.dot(y))

[[19. 22.]
 [43. 50.]]


In [ ]:
print(np.sum(x))

10.0


In [ ]:
print(np.sum(x,axis=0))

[4. 6.]


In [ ]:
print(np.sum(x,axis=1))

[3. 7.]


In [ ]:
print(np.transpose,x.T)

<function transpose at 0x7f0e33b65fc0> [[1. 3.]
 [2. 4.]]


In [ ]:
print("Random",x)


Random [[1. 2.]
 [3. 4.]]
